version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace:cached
    command: sleep infinity
    environment:
      - NODE_ENV=development
    #healthcheck:
    #  test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
    #  interval: 30s
    #  timeout: 10s
    #  retries: 3
    #  start_period: 40s
    ports:
      - "3000:3000"

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 2s
      start_interval: 1s
    ports:
      - "5432:5432"
